title: Gloriously Awkward
author:
  name: Steven Watson Buehler
  email: steven@stevenwatsonbuehler.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A kid trapped in the body of a 50-something because of Asperger Disorder,
  Social Anxiety, and Arrested Development. These are my stories of how I 
  handle faith and life on my own. 

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: facebook,       user_url: "https://www.facebook.com/stevenwatsonbuehler" }
    - { platform: instagram,      user_url: "https://www.instagram.com/stevenwatsonbuehler" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/stevenwbuehler" }
    - { platform: twitter,        user_url: "https://twitter.com/stevenwbuehler" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@stevenwbuehler" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
